---
galaxy_info:
  role_name: vault_server
  author: Thomas Fx
  description: Déploie HashiCorp Vault en production mode (Raft, SSH OTP, DB dynamic secrets, Transit, AppRole)
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["all"]

dependencies: []
