---
- name: Add HashiCorp repository
  become: true
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    creates: /etc/yum.repos.d/hashicorp.repo

- name: Install boundary
  become: true
  ansible.builtin.dnf:
    name: boundary
    state: present
