---
- name: Install Boundary
  ansible.builtin.import_tasks: install.yml

- name: Configure Boundary
  ansible.builtin.import_tasks: configure.yml

- name: Bootstrap Boundary
  ansible.builtin.import_tasks: bootstrap.yml
