---
- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true

- name: Enable and start chrony
  ansible.builtin.systemd:
    name: chrony
    enabled: true
    state: started

- name: Force NTP sync
  ansible.builtin.command: chronyc makestep
  changed_when: true
  notify: Restart chrony
