all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/devsecops
    ansible_python_interpreter: /usr/bin/python3

  children:
    vault_servers:
      hosts:
        vault-server:
          ansible_host: 10.0.0.10

    spire_servers:
      hosts:
        spire-server:
          ansible_host: 10.0.0.11

    workloads:
      hosts:
        workload-a:
          ansible_host: 10.0.0.20
        workload-b:
          ansible_host: 10.0.0.21
