---
- name: Install SPIRE server
  ansible.builtin.import_tasks: install.yml

- name: Configure SPIRE server
  ansible.builtin.import_tasks: configure.yml

- name: Bootstrap SPIRE server
  ansible.builtin.import_tasks: bootstrap.yml
