---
- name: Install prerequisites
  ansible.builtin.apt:
    name: [gnupg, curl, unzip, jq]
    state: present
    update_cache: true

- name: Add HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    mode: "0644"

- name: Add HashiCorp apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc]
      https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: hashicorp
    state: present

- name: Install Vault
  ansible.builtin.apt:
    name: vault
    state: present
    update_cache: true
