---
galaxy_info:
  role_name: spire_agent
  author: Thomas Fx
  description: Déploie SPIRE Agent avec join_token attestation et expose la Workload API
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["24.04"]

dependencies: []
